SCR_EditorAttributeList {
 m_aAttributes {
  CVON_EnableEspionage "{685F609D7C48A2DE}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{685F609D7D9615F0}" {
    Name "Enable Faction Encryption"
    Description "If disabled anyone from any faction can talk to each other on any frequency"
   }
   m_CategoryConfig "{EDD16BBBE3767070}Configs/Editor/AttributeCategories/GameSettings.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
  CVON_EnableBabbel "{685F6227B0737722}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{685F6227B073F5D8}" {
    Name "Enable Babbel"
    Description "If disabled anyone from any faction can talk to each other directly."
   }
   m_CategoryConfig "{EDD16BBBE3767070}Configs/Editor/AttributeCategories/GameSettings.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
 }
}